### ISSUE TITLE
EauthAuthenticationError at /djangosalt/minions/

### ISSUE THREAD

**Issue by yindashan** [holmboe/django-saltapi#4]
When I deploy the project on the apache,it reports the wrong:
EauthAuthenticationError at /djangosalt/minions/
Failed to authenticate, is this user permitted to execute commands?
why?

**Comment by holmboe** [comment]
Which user are you running Apache? And what does your authentication (`external_auth`) look like in the Salt master configuration file?

**Comment by yindashan** [comment]
I'm sorry,I make it,Thank you!
